spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    settlement:
      hostname: null
      username: null
      password: null
server:
  error:
    include-message: always